version: '3'

services:
 repo:
  build: .
  volumes:
    - ./arch:/var/www/html
  labels:
      - "traefik.enable=true"
      # HTTPS Rules
      - "traefik.http.routers.repo_SSL.rule=Host(`repo.odex.be`) || Host(`repo.pbfp.xyz`)"
      - "traefik.http.routers.repo_SSL.entrypoints=https"
      - "traefik.http.routers.repo_SSL.tls.certresolver=letsencrypt"
      - "traefik.http.routers.repo_SSL.tls=true"
      - "traefik.http.services.repo_SSL.loadbalancer.server.port=80"
      # HTTP
      - "traefik.http.routers.repo.rule=Host(`repo.odex.be`) || Host(`repo.pbfp.xyz`)"
      - "traefik.http.routers.repo.entrypoints=http"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.repo.middlewares=https-redirect"
  networks:
    - web
  restart: unless-stopped

networks:
  web:
     external: true
