version: '3'

services:
   web:
     build: .
     networks:
             - web
     labels:
       - "traefik.enable=true"
       # HTTPS Rules
       - "traefik.http.routers.site_SSL.rule=Host(`www.odex.be`) || Host(`www.pbfp.xyz`)"
       - "traefik.http.routers.site_SSL.entrypoints=https"
       - "traefik.http.routers.site_SSL.tls.certresolver=letsencrypt"
       - "traefik.http.routers.site_SSL.tls=true"
       # HTTP
       - "traefik.http.routers.site.rule=Host(`www.odex.be`) || Host(`www.pbfp.xyz`)"
       - "traefik.http.routers.site.entrypoints=http"
       - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
       - "traefik.http.routers.site.middlewares=https-redirect"

networks:
 web:
  external: true
