version: '3'

services:
        web:
              build: .
              networks:
                      - web
              labels:
                - "traefik.enable=true"
                - "traefik.backend=website"
                - "traefik.docker.network=web"
                - "traefik.frontend.rule=Host:www.pbfp.xyz,pbfp.xyz"
                - "traefik.port=80"
networks:
        web:
                external: true
