version: '3'

services:
 hugo:
  image: jojomi/hugo:latest
  volumes:
    - "./src/:/src"
    - work:/output
  environment:
    - HUGO_REFRESH_TIME=3600
    - HUGO_THEME=kross-hugo-portfolio-template
    - HUGO_BASEURL=https://tos.pbfp.xyz
  restart: unless-stopped

 web:
  image: jojomi/nginx-static
  volumes:
    - work:/var/www
  environment:
    - VIRTUAL_HOST=tos.pbfp.xyz
  ports:
    - 80
  labels:
      - "traefik.enable=true"
      # HTTPS Rules
      - "traefik.http.routers.tos_SSL.rule=Host(`tos.odex.be`) || Host(`tos.pbfp.xyz`)"
      - "traefik.http.routers.tos_SSL.entrypoints=websecure"
      - "traefik.http.routers.tos_SSL.tls.certresolver=myhttpchallenge"
      # HTTP redirect
      - "traefik.http.routers.tos.entryPoints=web"
      - "traefik.http.routers.tos.middlewares=https_redirect"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
  networks:
    - web
  restart: unless-stopped

networks:
  web:
     external: true

volumes:
  work:
