version: "3.3"

services:

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: unless-stopped
    labels:
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.tlsredirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/auth/management.auth"
      - "traefik.http.middlewares.compress.compress=true"
      - "traefik.http.middlewares.errorhandler.errors.status=400-599"
      - "traefik.http.middlewares.errorhandler.errors.service=error"
      - "traefik.http.middlewares.errorhandler.errors.query=/{status}.html"
      - "traefik.http.middlewares.inflight.inflightreq.amount=10"
      - "traefik.http.middlewares.retry.retry.attempts=4"
      # HTTPS Rules
      - "traefik.http.routers.traefik_SSL.rule=Host(`traefik.odex.be`) || Host(`traefik.pbfp.xyz`)"
      - "traefik.http.routers.traefik_SSL.entrypoints=https"
      - "traefik.http.routers.traefik_SSL.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik_SSL.tls=true"
      - "traefik.http.routers.traefik_SSL.service=api@internal"
      # HTTP
      - "traefik.http.routers.traefik.rule=Host(`traefik.odex.be`) || Host(`traefik.pbfp.xyz`)"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.middlewares=https-redirect"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./logs/:/logs"
      - "./traefik.yaml:/etc/traefik/traefik.yaml"
    networks:
      - web

networks:
  web:
   external: true
