api:
  insecure: true
  dashboard: true
providers:
  docker: true
providers:
  docker:
    network: web
    exposedbydefault: false
entrypoints:
  http:
    address: ":80"
  https:
    address: ":443"
certificatesresolvers:
  letsencrypt:
    acme:
      httpchallenge:
        entrypoint: http
      email: tom@odex.be
      storage: /letsencrypt/acme.json
accessLog:
  filePath: /logs/access.log
  bufferingSize: 100
log:
  level: DEBUG
global:
    sendAnonymousUsage: false
