version: '2'
services:
  phabricator:
    restart: always
    ports:
    #- "62443:443"
    #- "62080:80"
     - "62022:22"
    volumes:
     - /srv/docker/phabricator/repos:/repos
     - /srv/docker/phabricator/extensions:/srv/phabricator/phabricator/src/extensions
     - ./support/preamble.php:/srv/phabricator/phabricator/support/preamble.php
    depends_on:
     - mysql
    links:
     - mysql
    environment:
     - MYSQL_HOST=mysql
     - MYSQL_USER=root
     - MYSQL_PASS=phabricator
     - PHABRICATOR_REPOSITORY_PATH=/repos
     - PHABRICATOR_HOST=wiki.pbfp.xyz
     - SSL_TYPE=external
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.phabricator_ssl.rule=Host(`wiki.odex.be`) || Host(`wiki.pbfp.xyz`)"
     - "traefik.http.routers.phabricator_ssl.entrypoints=https"
     - "traefik.http.routers.phabricator_ssl.tls.certresolver=letsencrypt"
     - "traefik.http.routers.phabricator_ssl.tls=true"
     # HTTP
     - "traefik.http.routers.phabricator.rule=Host(`wiki.odex.be`) || Host(`wiki.pbfp.xyz`)"
     - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
     - "traefik.http.routers.phabricator.entrypoints=http"
     - "traefik.http.routers.phabricator.middlewares=https-redirect"
    networks:
     - web
    image: redpointgames/phabricator
  mysql:
    restart: always
    volumes:
     - /srv/docker/phabricator/mysql:/var/lib/mysql
    image: mysql:5.7.14
    environment:
     - MYSQL_ROOT_PASSWORD=phabricator
    networks:
     - web

networks:
  web:
    external: true
