version: '3'

services:
   jenkins:
      image: jenkinsci/blueocean:latest
      user: root
      restart: unless-stopped
      networks:
        - web
      ports:
        - "4205:4200"
        - "50000:50000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - jenkins_home:/var/jenkins_home
      logging:
         driver: none

      #environment:
      #  - JENKINS_HOME=/var/jenkins_home
      labels:
        - "traefik.enable=true"
        # HTTPS Rules
        - "traefik.http.routers.jenkins_SSL.rule=Host(`jenkins.odex.be`) || Host(`jenkins.pbfp.xyz`)"
        - "traefik.http.routers.jenkins_SSL.entrypoints=https"
        - "traefik.http.routers.jenkins_SSL.tls.certresolver=letsencrypt"
        - "traefik.http.routers.jenkins_SSL.tls=true"
        - "traefik.http.services.jenkins_SSL.loadbalancer.server.port=8080"
        # HTTP
        - "traefik.http.routers.jenkins.rule=Host(`jenkins.odex.be`) || Host(`jenkins.pbfp.xyz`)"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.jenkins.entrypoints=http"
        - "traefik.http.routers.jenkins.middlewares=https-redirect"
        
networks:
 web:
   external: true

volumes:
 jenkins_home:
