version: '3'

services:
   jenkins:
      image: jenkinsci/blueocean
      user: root
      networks:
        - web
      ports:
        - "4205:4200"
        - "50000:50000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - jenkins_home:/var/jenkins_home
 
      #environment:
      #  - JENKINS_HOME=/var/jenkins_home
      labels:
        - "traefik.enable=true"
        # HTTPS Rules
        - "traefik.http.routers.tos_SSL.rule=Host(`jenkins.odex.be`) || Host(`jenkins.pbfp.xyz`)"
        - "traefik.http.routers.tos_SSL.entrypoints=websecure"
        - "traefik.http.routers.tos_SSL.tls.certresolver=myhttpchallenge"
        # HTTP redirect
        - "traefik.http.routers.tos.entryPoints=web"
        - "traefik.http.routers.tos.middlewares=https_redirect"
        - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
networks:
 web:
   external: true

volumes:
 jenkins_home:
