version: '2'

services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    networks:
      - web
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      # HTTPS Rules
      - "traefik.http.routers.port_SSL.rule=Host(`port.odex.be`) || Host(`port.pbfp.xyz`)"
      - "traefik.http.routers.port_SSL.entrypoints=https"
      - "traefik.http.routers.port_SSL.tls.certresolver=letsencrypt"
      - "traefik.http.routers.port_SSL.tls=true"
      - "traefik.http.services.port_SSL.loadbalancer.server.port=9000"
      # HTTP
      - "traefik.http.routers.port.rule=Host(`port.odex.be`) || Host(`port.pbfp.xyz`)"
      - "traefik.http.routers.port.entrypoints=http"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.port.middlewares=https-redirect"

volumes:
  portainer_data:

networks:
  web:
    external: true
