version: '2'

services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    networks:
      - web
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      # HTTPS Rules
      - "traefik.http.routers.tos_SSL.rule=Host(`port.odex.be`) || Host(`port.pbfp.xyz`)"
      - "traefik.http.routers.tos_SSL.entrypoints=websecure"
      - "traefik.http.routers.tos_SSL.tls.certresolver=myhttpchallenge"
      # HTTP redirect
      - "traefik.http.routers.tos.entryPoints=web"
      - "traefik.http.routers.tos.middlewares=https_redirect"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"

volumes:
  portainer_data:

networks:
  web:
    external: true
