version: '3'

services:
 error:
  image: nginx
  container_name: error
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./pages:/usr/share/nginx/error-pages
  labels:
    traefik.enable: "true"

    traefik.http.routers.error-router_SSL.rule: HostRegexp(`{host:.+}`)
    traefik.http.routers.error-router_SSL.priority: 1
    traefik.http.routers.error-router_SSL.tls.certresolver: letsencrypt
    traefik.http.routers.error-router_SSL.tls: true
    traefik.http.routers.error-router_SSL.entrypoints: https
    traefik.http.routers.error-router_SSL.middlewares: error-pages-middleware
    
    traefik.http.routers.error-router.rule: HostRegexp(`{host:.+}`)
    traefik.http.routers.error-router.priority: 1
    traefik.http.routers.error-router.tls: false
    traefik.http.routers.error-router.entrypoints: http
    traefik.http.routers.error-router.middlewares: error-pages-middleware
  
    traefik.http.middlewares.error-pages-middleware.errors.status: 400-599
    traefik.http.middlewares.error-pages-middleware.errors.service: error-pages-service
    traefik.http.middlewares.error-pages-middleware.errors.query: /{status}.html

    traefik.http.services.error-pages-service.loadbalancer.server.port: 80

  networks:
    - web
  restart: unless-stopped

networks:
  web:
     external: true
