version: '2'
services:
  app:
    build: .
    depends_on:
      - redis
    command: npm start -- --port 80 --redis redis:6379
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scrumblr_SSL.rule=Host(`scrumblr.odex.be`) || Host(`scrumblr.pbfp.xyz`)"
      - "traefik.http.routers.scrumblr_SSL.entrypoints=https"
      - "traefik.http.routers.scrumblr_SSL.tls.certresolver=letsencrypt"
      - "traefik.http.routers.scrumblr_SSL.tls=true"
      # HTTP
      - "traefik.http.routers.scrumblr.rule=Host(`scrumblr.odex.be`) || Host(`scrumblr.pbfp.xyz`)"
      - "traefik.http.routers.scrumblr.entrypoints=http"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.scrumblr.middlewares=https-redirect"

  redis:
    image: redis
    networks:
      - web
    volumes:
      - redis_data:/var/lib/redis

volumes:
  redis_data:
    driver: local

networks:
        web:
                external: true
